In [1]:
import torch
from torch.autograd import Variable

In [3]:
a = Variable(torch.ones(2,2), requires_grad=True)
a

tensor([[ 1.,  1.],
        [ 1.,  1.]])

In [4]:
b = Variable(torch.ones(2,2), requires_grad=True)

In [5]:
print(a+b)

tensor([[ 2.,  2.],
        [ 2.,  2.]])


$y_i = 5(x_i + 1)^2$

In [19]:
x = Variable(torch.ones(2), requires_grad=True)

In [20]:
y = 5 * (x + 1) ** 2
y

tensor([ 20.,  20.])

$o = 1/2 \Sigma y_i$

In [21]:
o = (1/2) * torch.sum(y)
o

tensor(20.)

In [18]:
o.backward()

Gradient of $1/2 \Sigma 5(x_i + 1)^2$ with respect to x_i

In [12]:
x.grad

tensor([ 10.,  10.])

In [22]:
o.backward(torch.FloatTensor([1., 1.]))
x.grad

tensor([ 10.,  10.])