In [3]:
import torch
import numpy as np

In [6]:
arr = [[1, 2], [3, 4]]
np.array(arr)

array([[1, 2],
       [3, 4]])

In [5]:
torch.Tensor(arr)

tensor([[ 1.,  2.],
        [ 3.,  4.]])

In [7]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [8]:
torch.ones((2,2))

tensor([[ 1.,  1.],
        [ 1.,  1.]])

In [11]:
np.random.seed(0)
np.random.rand(2,2)

array([[0.12420691, 0.41156997],
       [0.90769275, 0.01185911]])

In [15]:
torch.manual_seed(0)
torch.rand(2,2)

tensor([[ 0.4963,  0.7682],
        [ 0.0885,  0.1320]])

In [16]:
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(0)

In [18]:
np_array = np.ones((2,2))
torch_tensor = torch.from_numpy(np_array)

In [21]:
np_array_new = np.ones((2,2), dtype=np.int64)
torch.from_numpy(np_array_new)
# supported types: double, float, float16, int64, int32, and uint8

tensor([[ 1,  1],
        [ 1,  1]])

int64 LongTensor

int32 IntegerTensor

uint8 ByteTensor

float64 DoubleTensor

float32 FloatTensor

double DoubleTensor

In [22]:
torch_tensor = torch.ones(2,2)
torch_to_numpy = torch_tensor.numpy()

In [23]:
tensor_cpu = torch.ones(2,2)

In [24]:
# have to put tensors on the gpu to run models smoothly
if torch.cuda.is_available():
    tensor_cpu.cuda()

In [25]:
tensor_cpu.cpu()

tensor([[ 1.,  1.],
        [ 1.,  1.]])

# Size

In [26]:
a = torch.ones(2,2)
print(a)

tensor([[ 1.,  1.],
        [ 1.,  1.]])


In [27]:
print(a.size())

torch.Size([2, 2])


In [28]:
a.view(4)

tensor([ 1.,  1.,  1.,  1.])

In [29]:
a.view(4).size()

torch.Size([4])

# Element-wise Addition

In [30]:
b = torch.ones(2,2)

In [32]:
c = a + b
print(c)

tensor([[ 2.,  2.],
        [ 2.,  2.]])


In [34]:
c = torch.add(a, b)
print(c)

tensor([[ 2.,  2.],
        [ 2.,  2.]])


In [35]:
# in place
c.add_(a)

tensor([[ 3.,  3.],
        [ 3.,  3.]])

In [36]:
a - b

tensor([[ 0.,  0.],
        [ 0.,  0.]])

In [37]:
# not in place
a.sub(b)

tensor([[ 0.,  0.],
        [ 0.,  0.]])

In [39]:
# in place
a.sub_(b)

tensor([[ 0.,  0.],
        [ 0.,  0.]])

In [42]:
a * b 

tensor([[ 0.,  0.],
        [ 0.,  0.]])

In [43]:
torch.mul(a, b) # also a.mul_(b)

tensor([[ 0.,  0.],
        [ 0.,  0.]])

In [44]:
torch.div(a, b)

tensor([[ 0.,  0.],
        [ 0.,  0.]])

In [51]:
a = torch.Tensor([1, 2, 3, 4, 5])
a.size()

torch.Size([5])

In [49]:
a.mean(dim=0)

tensor([ 1.,  2.,  3.,  4.,  5.])

In [53]:
a = torch.Tensor([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]])
a.size()
a.mean(dim=1)

tensor([ 3.,  3.])

In [55]:
a.std(dim=1)

tensor([ 1.5811,  1.5811])